export {Icon_arrow} from "./Icon_arrow"
export {Icon_instagram} from "./Icon_instagram"
export {Icon_facebook} from "./Icon_facebook"
export {Icon_tiktok} from "./Icon_tiktok"
export {Icon_youtube} from "./Icon_youtube"